// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "4d0e6ce3-25c4-4d25-973b-6d35a88f10ed");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575638229);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575638349);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575637989);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575638109);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575637749);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575637869);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575638469);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1546596917);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2bb65193-b734-42a9-9ee0-abc0611931d9}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1546540200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575639654862");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575641425862");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575637821048");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575641421048");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704192850");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575637794");
user_pref("browser.slowStartup.averageTime", 34017);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20180704192850");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1546596928434");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Fri, 06 Dec 2019 11:39:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1575638233);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704192850");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"06212377-aaf1-4418-86e8-67d4f8424eb2\",\"screenshots@mozilla.org\":\"441f8010-c53c-4401-a41d-727bf68b8de3\"}");
user_pref("idle.lastDailyNotification", 1575637939);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575637817);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180704192850");
user_pref("media.gmp-manager.lastCheck", 1575637807);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.type", 4);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575637965);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "00adc800-3225-4ba3-a4fc-6fd70df5f8f7");
user_pref("services.blocklist.addons.checked", 1575638302);
user_pref("services.blocklist.gfx.checked", 1575638302);
user_pref("services.blocklist.onecrl.checked", 1575638302);
user_pref("services.blocklist.pinning.checked", 1575638302);
user_pref("services.blocklist.plugins.checked", 1575638302);
user_pref("services.settings.clock_skew_seconds", 47);
user_pref("services.settings.last_etag", "\"1575632376941\"");
user_pref("services.settings.last_update_seconds", 1575638302);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575637965);
user_pref("toolkit.startup.last_success", 1575637667);
user_pref("toolkit.telemetry.cachedClientID", "f27b5612-94bf-4d16-8e20-d2b1174ad43f");
user_pref("toolkit.telemetry.previousBuildID", "20180704192850");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
